# .goreleaser.yml
# Build customization
project_name: kube-cleanup-operator

builds:
  - id: build
    binary: kube-cleanup-operator
    main: ./cmd/main.go
    env:
    - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: lwolf
    name: kube-cleanup-operator
  prerelease: true

dockers:
  - id: release-amd64
    dockerfile: Dockerfile.releaser
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - build
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    image_templates:
      - "quay.io/lwolf/kube-cleanup-operator:{{ .Version }}-amd64"

  - id: release-arm64
    dockerfile: Dockerfile.releaser
    use: buildx
    goos: linux
    goarch: arm64
    ids:
      - build
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    image_templates:
      - "quay.io/lwolf/kube-cleanup-operator:{{ .Version }}-arm64"

docker_manifests:
  - id: manifest-release
    name_template: "quay.io/lwolf/kube-cleanup-operator:{{ .Version }}"
    image_templates:
      - "quay.io/lwolf/kube-cleanup-operator:{{ .Version }}-amd64"
      - "quay.io/lwolf/kube-cleanup-operator:{{ .Version }}-arm64"

  - id: manifest-latest
    name_template: "quay.io/lwolf/kube-cleanup-operator:latest"
    image_templates:
      - "quay.io/lwolf/kube-cleanup-operator:{{ .Version }}-amd64"
      - "quay.io/lwolf/kube-cleanup-operator:{{ .Version }}-arm64"
